### ISSUE TITLE
Problem using library built with emscripten

### ISSUE THREAD

**Issue by CikaLaza** [akontsevich/openssl-android-build#2]
Hi,
I tried your scripts for building with emcc 1.38.30 on Ubuntu 18.04 and got both crypto and ssl .a and .so files. But when I try to link against those libraries, I/m getting error: undefined symbol: SSL_library_init. Strange thing is that those libraries contain only .o files (shouldn't there be .bc? ).
Libs added with _LIBS += -L..../libs/wasm/libssl.a_

I just started using emscripten so I might doing something wrong.. 

PS. Using openssl-1.0.2r

**Comment by akontsevich** [comment]
For emscripten it produces `.bc` files for me: https://stackoverflow.com/q/54034576/630169
Your link error could appear because of parameters in [config-params.txt](https://github.com/akontsevich/openssl-android-build/blob/master/config-params.txt) file. Play with them (add/remove) to enable necessary symbols you need and rebuild the library then.

**Comment by CikaLaza** [comment]
I managed to link shared libs, thanks.
