### ISSUE TITLE
'SSL handshake failed' on 64 bit android

### ISSUE THREAD

**Issue by jcusters** [akontsevich/openssl-android-build#3]
I have spend 2 days making arm64-v8a openSSL 1.0.2 libs, and was only capable of doing so with your build kit. Excellent work, thanx.

Only thing is that I ( and other users ) get an SSL handshake failed Error when using it with Qt 5.12. 
see https://bugreports.qt.io/browse/QTBUG-73474 for more details. 
This is only for the arm64-v8a , the armeabi-v7a works.

I build the libs on an OSX computer:
OPENSSL_VERSION="openssl-1.0.2o"
NDK android-ndk-r10e
using build-android.sh

Do you have any suggestion , or experience with this issue ? 
any help would be appreciated.

**Comment by akontsevich** [comment]
Try to use android-ndk-r18b for this. Also play with `config-params.txt` set.

**Comment by jcusters** [comment]
I'm sorry, this creates other failures:

r18b has no gcc compiler so forced to use build-android-clang.sh, this generates a : 
`AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "obj_cleanup_defer" referenced by "/data/app/com.mycompagny.myapp==/lib/arm64/libcrypto.so"...`

config-params.txt is not used in build-android-clang.sh, but as the 32 bit version works i suspect these params are ok.

**Comment by akontsevich** [comment]
Yes, latest Androids versions have only CLANG. So if You need arm64-v8a build it with clang.

**Comment by ndorando** [comment]
I'm afraid I experience the same issues. Building this on MacOS with clang, using ndk r18b or r19c leads to the 32 bit version working just fine but the 64 bit version generating QNetworkReply::SslHandshakeFailedError on the same device during runtime.

From what I can tell, the libs do get generated just fine and I can find them in the copied ressources in the build directory as well.
Nontheless, the arm64-v8a version doesn't seem to play nice with Qt. Did you manage to solve the issue @jcusters ?

**Comment by akontsevich** [comment]
Strange 64 bit worked fine for me.

**Comment by jcusters** [comment]
No, I'm waiting for Qt to add openSSL support for version 1.1.1 : QTBUG-71391 or fix it QTBUG-73474
@akontsevich : it's probably a fault in Qt's supportSSL function, some report that if you ignore the handshake error, it then works, but for obvious reasons we do not choose this solution.

**Comment by ndorando** [comment]
So let's hope it is indeed a Qt bug that is fixed rather sooner than later. Thank you for mentioning the Bugreports @jcusters . Someone in the second report mentioned this: https://github.com/KDAB/android_openssl/tree/1.0.x/aarch64 as a precompiled alternative. This seems to work just fine for me as a drop-in replacement for the moment until Qt fixes it's stuff (in 12.5 I believe?).
If you need a fix urgently (since Googles 64-bit deadline looms), this seems to do what it's supposed to do - even if precompiled.

There also seem to be build scripts in the same repo, that might also help you @akontsevich compare yours to, if you're interested in that. However, from the bugreports, it seems to be a Qt specific issue that, not necessarily an issue in your scripts.

**Comment by jcusters** [comment]
Confirmed it also through extensive test:
For standard released kit: Android for arm64-v8a (Clang Qt 5.12.3 for Android ARM64-v8a)
and aarch64 libraries from: https://github.com/KDAB/android_openssl/tree/1.0.x
64bit lib works as expected ( same as 32bit )
thanks for the help
